set serveroutput on
begin
--  loc_trans_pkg.load_application_control;
--  list_trans_pkg.load_prev_svc_type;
--  list_trans_pkg.load_prev_svc_type_lang;
--  list_trans_pkg.load_billing_type;
--  list_trans_pkg.load_billing_type_lang;
--  list_trans_pkg.load_prev_svc_billing;
--  list_trans_pkg.load_prev_svc_billing_lang;
--  list_trans_pkg.load_question_score_type;
--  list_trans_pkg.load_question_categ_grp;
--  list_trans_pkg.load_question_categ_grp_lang;
--  list_trans_pkg.load_categ_condition;
--  list_trans_pkg.load_question_categ;
--  list_trans_pkg.load_svc_bq_categ;
--  list_trans_pkg.load_question_sub_categ;
--  list_trans_pkg.load_response;
--  list_trans_pkg.load_question;
--  --
--  list_trans_pkg.load_race;
--  list_trans_pkg.load_ethnicity;
--  list_trans_pkg.load_income;
--  list_trans_pkg.load_working_status;
--  list_trans_pkg.load_gender;
--  list_trans_pkg.load_education_level;
--  list_trans_pkg.load_marital_status;
--  list_trans_pkg.load_financial_status;
--  list_trans_pkg.load_living_status;
--  list_trans_pkg.load_physician_type;
--  list_trans_pkg.load_svc_location_type;
--  list_trans_pkg.load_frequency_unit;
--  list_trans_pkg.load_disease_level;
--  list_trans_pkg.load_categ_score_eval;
--  --
--  list_trans_pkg.load_height;
--  list_trans_pkg.load_weight;
--  list_trans_pkg.load_systolic_bp;
--  list_trans_pkg.load_diastolic_bp;
--  list_trans_pkg.load_blood_sugar_level;
--  list_trans_pkg.load_cholesterol;
--  list_trans_pkg.load_patient_orientation;
  --
--  list_trans_pkg.load_prev_plan;
--  list_trans_pkg.load_disease_type;
--  list_trans_pkg.load_disease_categ;
--  list_trans_pkg.load_disease;
--  list_trans_pkg.load_risk_factor_categ;
--  list_trans_pkg.load_risk_factor;
--  list_trans_pkg.load_severity;
--  list_trans_pkg.load_disease_severity;
--  list_trans_pkg.load_disease_risk_factor;
--  list_trans_pkg.load_disease_prev_plan;
--  list_trans_pkg.load_risk_factor_prev_plan;

--  
--  list_trans_pkg.load_symptom_categ;
--  list_trans_pkg.load_symptom;
--  list_trans_pkg.load_disease_symptom;
--  --
--  list_trans_pkg.load_em_categ_grp;
--  list_trans_pkg.load_em_categ;
--  list_trans_pkg.load_em_name;
--  list_trans_pkg.load_ccm_question_categ;
--  list_trans_pkg.load_ccm_question;
--  list_trans_pkg.load_am_pm;
--  list_trans_pkg.load_min;
--  list_trans_pkg.load_hr;
--  --
  --
--  list_trans_pkg.load_question_response('I');
  ----------------------list_trans_pkg.upd_list_measurement;
  --
--  list_trans_pkg.load_priviledge_type;
--  list_trans_pkg.load_priviledge;
--  list_trans_pkg.load_ui;
--  list_trans_pkg.load_roles_priviledge;
--  list_trans_pkg.load_priviledge_ui;
  --
--  common_trans_pkg.load_control_data;  
end;
/